name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Test Coverage
      run: | 
       go test "./..." -coverprofile="sonar_coverage.out" -covermode=count -json > sonar_report.json
       go tool cover -html=sonar_coverage.out -o coverage.html
       
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: code-coverage-report
        path: |
          coverage.*
          sonar_*
